export const courses = [
  "Bachelor of Computer Application",
  "Computer Science and Engineering",

  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Environmental Engineering",
  "Materials Science and Engineering",
  "Industrial Engineering",
  "Information Technology",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Robotics",
  "Physics",
  "Mathematics",
  "Chemistry",
  "Biology",
  "Business Administration",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Human Resources",
  "Psychology",
  "Sociology",
  "Political Science",
  "History",
  "English Literature",
  "Philosophy",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Law",
  "Architecture",
  "Fine Arts",
  "Music",
  "Other"
];